
import java.awt.BorderLayout;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.TransferHandler;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.data.statistics.HistogramDataset;
import org.jfree.data.xy.IntervalXYDataset;
import org.jfree.ui.RefineryUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gaby
 */
public class Principal extends javax.swing.JFrame {

    DefaultTableModel model;
    Object[] llenar = new Object[2];

    float suma = 0;
    float suma2 = 0;
    float suma3 = 0;
    float suma4 = 0;
    float suma5 = 0;
    float suma6 = 0;
    float suma1_1 = 0;
    float suma2_2 = 0;
    float suma3_3 = 0;
    float suma4_4 = 0;

    public Principal() {
        initComponents();

        model = new DefaultTableModel();
        model.addColumn("X");
        model.addColumn("Y");
        pnlFondo fondo = new pnlFondo(1366, 768);
        this.add(fondo, BorderLayout.CENTER);
        //model.addRow(llenar);

        jTableDatos.setModel(model);

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField_dediana_X = new javax.swing.JTextField();
        jTextFieldmoda = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField_ran_X = new javax.swing.JTextField();
        jTextField_min_X = new javax.swing.JTextField();
        jTextField_max_X = new javax.swing.JTextField();
        jTextFieldSuma = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_dediana_Y = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField16moday = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField_ran_Y = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField_min_Y = new javax.swing.JTextField();
        jTextField_max_Y = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldSuma1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField25a = new javax.swing.JTextField();
        jTextField26b = new javax.swing.JTextField();
        jTextField27c = new javax.swing.JTextField();
        jTextField28d = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField29m = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField30d = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField31ls = new javax.swing.JTextField();
        jTextField32li = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField25b0 = new javax.swing.JTextField();
        jTextField26b1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jTextField29xx = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "INGRESO DATOS"));

        jTableDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "X", "Y"
            }
        ));
        jScrollPane1.setViewportView(jTableDatos);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("X:");

        jLabel2.setText("Y:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Insertar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ESTADÍSTICA DESCRIPTIVA"));

        jLabel3.setText("MEDIA:");

        jLabel4.setText("MEDIANA:");

        jLabel5.setText("MODA:");

        jLabel6.setText("DESVIACIÓN EST.:");

        jLabel7.setText("VARIANZA:");

        jLabel8.setText("CURTOSIS:");

        jLabel9.setText("COEF. SIMETRÍA:");

        jLabel10.setText("RANGO:");

        jLabel11.setText("MÍNIMO:");

        jLabel12.setText("MÁXIMO:");

        jLabel13.setText("SUMA: ");

        jLabel14.setText("NÚMERO DATOS:");

        jTextField3.setEditable(false);

        jTextField_dediana_X.setEditable(false);

        jTextFieldmoda.setEditable(false);

        jTextField6.setEditable(false);

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);

        jTextField9.setEditable(false);

        jTextField_ran_X.setEditable(false);

        jTextField_min_X.setEditable(false);

        jTextField_max_X.setEditable(false);

        jTextFieldSuma.setEditable(false);

        jTextField14.setEditable(false);

        jLabel15.setText("MEDIA:");

        jTextField13.setEditable(false);

        jLabel16.setText("MEDIANA:");

        jTextField_dediana_Y.setEditable(false);

        jLabel17.setText("MODA:");

        jTextField16moday.setEditable(false);

        jLabel18.setText("DESVIACIÓN EST.:");

        jTextField17.setEditable(false);

        jLabel19.setText("VARIANZA:");

        jTextField18.setEditable(false);

        jLabel20.setText("CURTOSIS:");

        jTextField19.setEditable(false);

        jLabel21.setText("COEF. SIMETRÍA:");

        jTextField20.setEditable(false);

        jTextField_ran_Y.setEditable(false);

        jLabel22.setText("RANGO:");

        jLabel23.setText("MÍNIMO:");

        jTextField_min_Y.setEditable(false);

        jTextField_max_Y.setEditable(false);

        jLabel24.setText("MÁXIMO:");

        jTextFieldSuma1.setEditable(false);

        jLabel25.setText("SUMA: ");

        jLabel26.setText("NÚMERO DATOS:");

        jTextField24.setEditable(false);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Y");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldmoda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_dediana_X, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField14))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField9)
                                        .addComponent(jTextFieldSuma)
                                        .addComponent(jTextField_max_X)
                                        .addComponent(jTextField_min_X)
                                        .addComponent(jTextField_ran_X, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField16moday, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_dediana_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField24))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField20)
                                        .addComponent(jTextFieldSuma1)
                                        .addComponent(jTextField_max_Y)
                                        .addComponent(jTextField_min_Y)
                                        .addComponent(jTextField_ran_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField_dediana_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField16moday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextField_ran_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField_min_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField_max_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldSuma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_dediana_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldmoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_ran_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_min_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_max_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("INTERVALOS DE CONFIANZA PARA LA MEDIA "));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90%", "95%", "99%" }));

        jLabel27.setText("NIVEL DE CONFIANZA:");

        jLabel28.setText("NIVEL DE CONFIANZA:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "90%", "95%", "99%" }));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Y");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("X");

        jLabel33.setText("Media:");

        jLabel34.setText("Desviación Estandar:");

        jLabel35.setText("Límite Superior:");

        jLabel36.setText("Límite Inferior:");

        jTextField25a.setEditable(false);

        jTextField26b.setEditable(false);

        jTextField27c.setEditable(false);

        jTextField28d.setEditable(false);

        jLabel37.setText("Media:");

        jTextField29m.setEditable(false);

        jLabel38.setText("Desviación Estandar:");

        jTextField30d.setEditable(false);

        jLabel39.setText("Límite Superior:");

        jTextField31ls.setEditable(false);

        jTextField32li.setEditable(false);
        jTextField32li.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32liActionPerformed(evt);
            }
        });

        jLabel40.setText("Límite Inferior:");

        jButton6.setText("Calcular");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Calcular");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(71, 71, 71))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 78, Short.MAX_VALUE)
                                    .addComponent(jTextField25a)
                                    .addComponent(jTextField26b)
                                    .addComponent(jTextField27c)
                                    .addComponent(jTextField28d)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField29m, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jTextField30d)
                                    .addComponent(jTextField31ls)
                                    .addComponent(jTextField32li))))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField25a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextField26b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField27c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextField28d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(28, 28, 28)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jTextField29m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextField30d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jTextField31ls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTextField32li, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("COEF. CORRELACION Y REGRESION LINEAL"));
        jPanel3.setToolTipText("");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Estimadores MCO");

        jLabel42.setText("B(0): ");

        jLabel43.setText("B(1): ");

        jTextField25b0.setEditable(false);

        jTextField26b1.setEditable(false);

        jLabel44.setText("y:");

        jTextField27.setEditable(false);

        jLabel45.setText("e^2:");

        jTextField28.setEditable(false);

        jLabel46.setText("S(xx):");

        jLabel47.setText("S(yy):");

        jLabel48.setText("S(xy):");

        jLabel49.setText("r:");

        jLabel50.setText("r^2:");

        jTextField29xx.setEditable(false);

        jTextField30.setEditable(false);

        jTextField31.setEditable(false);

        jTextField32.setEditable(false);

        jTextField33.setEditable(false);

        jButton8.setText("Calcular");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Graficar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel41)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField31)
                            .addComponent(jTextField32)
                            .addComponent(jTextField33)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField25b0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField27, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jTextField28)
                            .addComponent(jTextField26b1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField29xx, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jTextField25b0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jTextField26b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jTextField29xx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton10.setText("Ver histograma");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        llenar[0] = jTextField1.getText();
        llenar[1] = jTextField2.getText();
        model.addRow(llenar);
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int a = jTableDatos.getSelectedRow();
        if (a < 0) {
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar una fila de la tabla");
        } else {

            int confirmar = JOptionPane.showConfirmDialog(null,
                    "Esta seguro que desea Eliminar ");
            if (JOptionPane.OK_OPTION == confirmar) {
                model.removeRow(a);
                JOptionPane.showMessageDialog(null,
                        "Registro Eliminado");

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        calcularX();
        calcularY();
        ordenar_vector();


    }//GEN-LAST:event_jButton3ActionPerformed
    double[] x, y;

    private void ordenar_vector() {
        int total = jTableDatos.getRowCount();
        x = new double[total];
        y = new double[total];
        for (int i = 0; i < total; i++) {
            x[i] = Double.valueOf(jTableDatos.getValueAt(i, 0).toString());
            y[i] = Double.valueOf(jTableDatos.getValueAt(i, 1).toString());
        }
        //moda
        int maximavecesx = 0;
        int maximavecesy = 0;
        int modax = 0;
        int moday = 0;
        for (int i = 0; i < x.length; i++) {
            int vecesRepetidasx = 0;
            int vecesRepetidasy = 0;
            x[i] = Double.valueOf(jTableDatos.getValueAt(i, 0).toString());
            y[i] = Double.valueOf(jTableDatos.getValueAt(i, 1).toString());
            for (int j = 0; j < x.length; j++) {
                x[j] = Double.valueOf(jTableDatos.getValueAt(j, 0).toString());
                y[j] = Double.valueOf(jTableDatos.getValueAt(j, 1).toString());
                if (x[i] == x[j] && y[i] == y[j]) {
                    vecesRepetidasx++;
                    vecesRepetidasy++;
                }
                if (vecesRepetidasx > maximavecesx && vecesRepetidasy > maximavecesy) {
                    modax = (int) x[i];
                    moday = (int) y[i];
                }
            }
            jTextFieldmoda.setText(String.valueOf(modax));
           jTextField16moday.setText(String.valueOf(moday));
        }
        ////
        ////
        for (int i = 0; i < total; i++) {
            for (int j = 0; j < total; j++) {
                if (x[i] > x[j]) {
                    //Intercambiamos valores
                    double variableauxiliar = x[i];
                    x[i] = x[j];
                    x[j] = variableauxiliar;

                }
                if (y[i] > y[j]) {
                    //Intercambiamos valores
                    double variableauxiliar = y[i];
                    y[i] = y[j];
                    y[j] = variableauxiliar;

                }
            }
        }
        int div = total % 2;
        //JOptionPane.showMessageDialog(this, "total = "+total+" div= "+div);
        if (div == 0) {
            int med = total / 2;
            float sumX = (float) (x[med] + x[med - 1]) / 2;
            float sumY = (float) (y[med] + y[med - 1]) / 2;
            jTextField_dediana_X.setText((String.valueOf(sumX)));
            jTextField_dediana_Y.setText((String.valueOf(sumY)));
        } else {
            int med = (total / 2);
            jTextField_dediana_X.setText((String.valueOf(x[med])));
            jTextField_dediana_Y.setText((String.valueOf(y[med])));
        }
        ////
        jTextField_min_X.setText((String.valueOf(x[total - 1])));
        jTextField_min_Y.setText((String.valueOf(y[total - 1])));
        jTextField_max_X.setText((String.valueOf(x[0])));
        jTextField_max_Y.setText((String.valueOf(y[0])));

        jTextField_ran_X.setText(String.valueOf(x[0] - x[total - 1]));
        jTextField_ran_Y.setText(String.valueOf(y[0] - y[total - 1]));
    }

    private void calcularY() throws NumberFormatException {
        double sumatoria1 = 0.0;
        int totalRow = jTableDatos.getRowCount();
        jTextField24.setText(String.valueOf(totalRow));
        totalRow -= 1;
        //
        for (int i = 0; i <= (totalRow); i++) {
            double sumatoria = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 1)));
            sumatoria1 += sumatoria;
            jTextFieldSuma1.setText(String.valueOf(sumatoria1));
        }
        //media
        float media = (float) sumatoria1 / jTableDatos.getRowCount();
        jTextField13.setText(String.valueOf(media));
        //mediana
        //moda
        //Desviacion estandar
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float res = (float) Math.pow((dato - media), 2);
            suma1_1 = suma1_1 + res;
        }
        float desv = (float) Math.sqrt(suma1_1 / totalRow);
        jTextField17.setText(String.valueOf(desv));
        //Varianza
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float res = (float) Math.pow((dato - media), 2);
            suma2_2 = suma2_2 + res;
        }
        float vari = suma2_2 / totalRow;
        jTextField18.setText(String.valueOf(vari));
        //Curtosis
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float res = (float) (dato - media) / desv;
            float resp = (float) Math.pow(res, 4);
            suma3_3 = suma3_3 + resp;

        }
        float curt = (float) ((totalRow + 1) * (totalRow + 2) * suma3_3);
        float curto = curt / ((totalRow) * (totalRow - 1) * (totalRow - 2));
        float curtos = (float) (3 * Math.pow(totalRow, 2));
        float curtosi = curtos / ((totalRow - 1) * (totalRow - 2));
        float curtosis = curto - curtosi;
        jTextField19.setText(String.valueOf(curtosis));
        ///Coef. Simetría
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float res = (float) (dato - media) / desv;
            float resp = (float) Math.pow(res, 3);
            suma4_4 = suma4_4 + resp;
        }
        float coe = (float) ((totalRow + 1) * suma4_4);
        float coef = coe / ((totalRow) * (totalRow - 1));
        jTextField20.setText(String.valueOf(coef));
        //       

    }
    
    private void calcularX() throws NumberFormatException {
        double sumatoria1 = 0.0;
        int totalRow = jTableDatos.getRowCount();
        jTextField14.setText(String.valueOf(totalRow));
        totalRow -= 1;
        //
        for (int i = 0; i <= (totalRow); i++) {
            double sumatoria = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 0)));
            sumatoria1 += sumatoria;
            jTextFieldSuma.setText(String.valueOf(sumatoria1));
        }
        //media
        float media = (float) sumatoria1 / jTableDatos.getRowCount();
        jTextField3.setText(String.valueOf(media));
        //mediana
        //moda
        //Desviacion estandar
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 0)));
            float res = (float) Math.pow((dato - media), 2);
            suma = suma + res;
        }
        float desv = (float) Math.sqrt(suma / totalRow);
        jTextField6.setText(String.valueOf(desv));
        //Varianza
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 0)));
            float res = (float) Math.pow((dato - media), 2);
            suma2 = suma2 + res;
        }
        float vari = suma2 / totalRow;
        jTextField7.setText(String.valueOf(vari));
        //Curtosis
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 0)));
            float res = (float) (dato - media) / desv;
            float resp = (float) Math.pow(res, 4);
            suma3 = suma3 + resp;

        }
        float curt = (float) ((totalRow + 1) * (totalRow + 2) * suma3);
        float curto = curt / ((totalRow) * (totalRow - 1) * (totalRow - 2));
        float curtos = (float) (3 * Math.pow(totalRow, 2));
        float curtosi = curtos / ((totalRow - 1) * (totalRow - 2));
        float curtosis = curto - curtosi;
        jTextField8.setText(String.valueOf(curtosis));
        ///Coef. Simetría
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 0)));
            float res = (float) (dato - media) / desv;
            float resp = (float) Math.pow(res, 3);
            suma4 = suma4 + resp;
        }
        float coe = (float) ((totalRow + 1) * suma4);
        float coef = coe / ((totalRow) * (totalRow - 1));
        jTextField9.setText(String.valueOf(coef));
    }


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser cargar = new JFileChooser();
        cargar.setFileFilter(new FileNameExtensionFilter("Archivos excel", "xls", "xlsx"));
        int opcion = cargar.showOpenDialog(this);
        File archivoExcel = null;
        if (opcion == JFileChooser.APPROVE_OPTION) {
            archivoExcel = cargar.getSelectedFile().getAbsoluteFile();
            try {
                Workbook leerExcel = Workbook.getWorkbook(archivoExcel);
                for (int hoja = 0; hoja < leerExcel.getNumberOfSheets(); hoja++) {
                    Sheet hojaf = leerExcel.getSheet(hoja);
                    int columnas = hojaf.getColumns();
                    int filas = hojaf.getRows();
                    Object data[] = new Object[columnas];
                    for (int fila = 0; fila < filas; fila++) {
                        for (int columna = 0; columna < columnas; columna++) {
                            if (fila == 0) {
                                //model.addColumn(hojaf.getCell(columna, fila).getContents());

                            }
                            if (fila >= 0) {
                                data[columna] = hojaf.getCell(columna, fila).getContents();
                            }

                        }
                        model.addRow(data);
                    }
                    //model.removeRow(0);
                }
            } catch (IOException | BiffException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed
    public boolean validarCampos() {
        if (jTextField1.equals("")) {
            return false;
        }
        if (jTextField2.equals("")) {
            return false;
        }
        return true;
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int fil = model.getRowCount() - 1;
        if (fil > 0) {
            for (int j = fil; j >= 0; j--) {
                model.removeRow(model.getRowCount() - 1);
            }
        }
        jTextField1.setText("");
        jTextField_dediana_Y.setText("");
        jTextField_ran_X.setText("");
        jTextField16moday.setText("");
        jTextField_min_X.setText("");
        jTextField17.setText("");
        jTextField_max_X.setText("");
        jTextField18.setText("");
        jTextField13.setText("");
        jTextField19.setText("");
        jTextField14.setText("");
        jTextField2.setText("");

        jTextField20.setText("");
        jTextField_ran_Y.setText("");
        jTextField_min_Y.setText("");
        jTextField_max_Y.setText("");
        jTextField24.setText("");
        jTextField25a.setText("");
        jTextField25b0.setText("");
        jTextField26b.setText("");
        jTextField26b1.setText("");
        jTextField27.setText("");
        jTextField27c.setText("");
        jTextField28.setText("");
        jTextField28d.setText("");
        jTextField29m.setText("");

        jTextField29xx.setText("");
        jTextField3.setText("");
        jTextField30.setText("");
        jTextField30d.setText("");
        jTextField31.setText("");
        jTextField31ls.setText("");
        jTextField32.setText("");
        jTextField32li.setText("");
        jTextField33.setText("");
        jTextField_dediana_X.setText("");
        jTextFieldmoda.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextFieldSuma.setText("");
        jTextFieldSuma1.setText("");


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        double sumatoria2 = 0.0;
        int totalRow = jTableDatos.getRowCount();
        totalRow -= 1;
        for (int i = 0; i <= (totalRow); i++) {
            double sumatoria = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 0)));
            sumatoria2 += sumatoria;
        }
        //media
        float media = (float) sumatoria2 / jTableDatos.getRowCount();
        //Desviacion estandar
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 0)));
            float res = (float) Math.pow((dato - media), 2);
            suma5 = suma5 + res;
        }
        float desv = (float) Math.sqrt(suma5 / totalRow);

        //
        if (jComboBox1.getSelectedItem() == "90%") {
            jTextField25a.setText(String.valueOf(media));
            jTextField26b.setText(String.valueOf(desv));
            float sigma = (float) (1 - 0.9) / 2;
            float z = (float) 1.645;
            float lims = (float) (media + z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            float limi = (float) (media - z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            jTextField27c.setText(String.valueOf(lims));
            jTextField28d.setText(String.valueOf(limi));
        }
        if (jComboBox1.getSelectedItem() == "95%") {
//            jTextField25a.setText(String.valueOf(media));
//            jTextField26b.setText(String.valueOf(desv));
            float sigma = (float) (1 - 0.95) / 2;
            float z = (float) 1.96;
            float lims = (float) (media + z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            float limi = (float) (media - z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            jTextField27c.setText(String.valueOf(lims));
            jTextField28d.setText(String.valueOf(limi));
        }
        if (jComboBox1.getSelectedItem() == "99%") {
//            jTextField25a.setText(String.valueOf(media));
//            jTextField26b.setText(String.valueOf(desv));
            float sigma = (float) (1 - 0.99) / 2;
            float z = (float) 2.575;
            float lims = (float) (media + z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            float limi = (float) (media - z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            jTextField27c.setText(String.valueOf(lims));
            jTextField28d.setText(String.valueOf(limi));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField32liActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32liActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32liActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        double sumatoria1 = 0.0;
        int totalRow = jTableDatos.getRowCount();
        jTextField24.setText(String.valueOf(totalRow));
        totalRow -= 1;
        //
        for (int i = 0; i <= (totalRow); i++) {
            double sumatoria = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 1)));
            sumatoria1 += sumatoria;
        }
        //media
        float media = (float) sumatoria1 / jTableDatos.getRowCount();
        //Desviacion estandar
        for (int i = 0; i <= (totalRow); i++) {
            float dato = Float.parseFloat(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float res = (float) Math.pow((dato - media), 2);
            suma6 = suma6 + res;
        }
        float desv = (float) Math.sqrt(suma6 / totalRow);
        //
        if (jComboBox2.getSelectedItem() == "90%") {
            jTextField29m.setText(String.valueOf(media));
            jTextField30d.setText(String.valueOf(desv));
            float sigma = (float) (1 - 0.9) / 2;
            float z = (float) 1.645;
            float lims = (float) (media + z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            float limi = (float) (media - z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            jTextField31ls.setText(String.valueOf(lims));
            jTextField32li.setText(String.valueOf(limi));
        }
        if (jComboBox2.getSelectedItem() == "95%") {
//            jTextField29m.setText(String.valueOf(media));
//            jTextField30d.setText(String.valueOf(desv));
            float sigma = (float) (1 - 0.95) / 2;
            float z = (float) 1.96;
            float lims = (float) (media + z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            float limi = (float) (media - z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            jTextField31ls.setText(String.valueOf(lims));
            jTextField32li.setText(String.valueOf(limi));
        }
        if (jComboBox2.getSelectedItem() == "99%") {
//            jTextField29m.setText(String.valueOf(media));
//            jTextField30d.setText(String.valueOf(desv));
            float sigma = (float) (1 - 0.99) / 2;
            float z = (float) 2.575;
            float lims = (float) (media + z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            float limi = (float) (media - z * (desv / Math.sqrt(jTableDatos.getRowCount())));
            jTextField31ls.setText(String.valueOf(lims));
            jTextField32li.setText(String.valueOf(limi));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        double sumatoria1 = 0.0;
        double sumatoria2 = 0.0;
        double sumat = 0.0;
        double yysum = 0.0;
        double xcuadrado = 0.0;
        double ycuadrado = 0.0;
        double sumaxy = 0.0;
        double sumae = 0.0;
        int totalRow = jTableDatos.getRowCount();
        totalRow -= 1;
        //
        for (int i = 0; i <= (totalRow); i++) {
            double dato = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 0)));
            double dato1 = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float xcua = (float) Math.pow(dato, 2);
            float ycua = (float) Math.pow(dato1, 2);
            float xy = (float) (dato * dato1);
            //suma de cada valor de x al cuadrado
            xcuadrado += xcua;
            ycuadrado += ycua;
            //suma de cada valor de x
            sumatoria1 += dato;
            sumatoria2 += dato1;
            sumaxy += xy;
        }
        //media
        float mediax = (float) sumatoria1 / jTableDatos.getRowCount();
        float mediay = (float) sumatoria2 / jTableDatos.getRowCount();
        //
        float sxx = (float) (xcuadrado - ((Math.pow(sumatoria1, 2)) / jTableDatos.getRowCount()));
        float syy = (float) (ycuadrado - ((Math.pow(sumatoria2, 2)) / jTableDatos.getRowCount()));
        float sxy = (float) (sumaxy - ((sumatoria1 * sumatoria2) / jTableDatos.getRowCount()));
        float r = (float) (sxy / Math.sqrt(sxx * syy));
        float r2 = (float) Math.pow(r, 2);
        jTextField29xx.setText(String.valueOf(sxx));
        jTextField30.setText(String.valueOf(syy));
        jTextField31.setText(String.valueOf(sxy));
        jTextField32.setText(String.valueOf(r));
        jTextField33.setText(String.valueOf(r2));
        for (int i = 0; i <= (totalRow); i++) {
            double dato = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 0)));
            float xx = (float) dato - mediax;
            float xx1 = (float) Math.pow(xx, 2);
            yysum += xx1;
            double dato1 = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float yy = (float) dato1 - mediay;
            sumat += xx * yy;
        }
        b1 = (float) (sumat / yysum);
        jTextField25b0.setText(String.valueOf(b1));
        b0 = mediay - (b1 * mediax);
        jTextField26b1.setText(String.valueOf(b0));
        jTextField27.setText(b0 + " + " + b1 + "x");
        for (int i = 0; i <= (totalRow); i++) {
            double datox = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 0)));
            float yestimado = (float) (b0 + (b1 * datox));
            //sumae+=Math.pow(yestimado, 2);
            double datoy = Double.parseDouble(String.valueOf(jTableDatos.getValueAt(i, 1)));
            float restae = (float) datoy - yestimado;
            sumae += Math.pow(restae, 2);
        }
        jTextField28.setText(String.valueOf(sumae));
    }//GEN-LAST:event_jButton8ActionPerformed
    float b0, b1;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        double[] xe = new double[30];
        double[] ye = new double[30];
        int val = 15;
        for (int i = 0; i < 30; i++) {
            xe[i] = val;
            val--;
            ye[i] = b0 + (xe[i] * b1);
        }
        JFrame frame = new JFrame("Gráfica");
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        JPanelColor jPanelColor = new JPanelColor(xe, ye, x, y); // create JPanelColor
        frame.add(jPanelColor); // agrega jPanelColor a marco
        frame.setSize(1000, 700); // establece el tamaño del marco
        frame.setVisible(true); // muestra el marco 

////        if(jEditorPane_Estru_Ecu.getText().equals("")){
////            JOptionPane.showMessageDialog(this,"No existe ecuacion a graficar.....!!");
////        }else{
//           double[] x = new double[30];
//        double[] y = new double[30];
//        ///////////llenado de valores x y
//        double val=15;
//        for (int i = 0; i < 30; i++) {
//            x[i]=val;
//            y[i]=y(cs,x[i]);
//            val--;
//            //JOptionPane.showMessageDialog(this, "x= "+x[i]+" y= "+y[i]);
////        }
//        
//        ////////////////////////7
//        
//        
//         JFrame frame = new JFrame( "Gráfica" );
//        frame.setDefaultCloseOperation( JFrame.HIDE_ON_CLOSE );
//        JPanelColor jPanelColor = new JPanelColor(x,y); // create JPanelColor
//        frame.add( jPanelColor ); // agrega jPanelColor a marco
//        frame.setSize( 1000, 700 ); // establece el tamaño del marco
//        frame.setVisible( true ); // muestra el marco 
//        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
    }//GEN-LAST:event_jButton10ActionPerformed
//    private IntervalXYDataset crearDataset() {
//        HistogramDataset dataset = new HistogramDataset();
//        int total = jTableDatos.getRowCount();
//        x = new double[total];
//        y = new double[total];
//        for (int i = 0; i < total; i++) {
//            x[i] = Double.valueOf(jTableDatos.getValueAt(i, 0).toString());
//            y[i] = Double.valueOf(jTableDatos.getValueAt(i, 1).toString());
//            dataset.addSeries("00", x, 10);
//        }
//
//        return dataset;
//    }
//
//    public JPanel crearPanel() {
//        JFreeChart chart = crearChart(crearDataset());
//        return new ChartPanel(chart);
//    }
//
//    private JFreeChart crearChart(IntervalXYDataset dataset) {
//        JFreeChart chart = ChartFactory.createHistogram("Histograma X", null, null, dataset, PlotOrientation.VERTICAL, true, true, false);
//        XYPlot plot = (XYPlot) chart.getPlot();
//        XYBarRenderer renderer = (XYBarRenderer) plot.getRenderer();
//        renderer.setDrawBarOutline(false);
//        return chart;
//    }

    public void tranferir(TransferHandler.TransferSupport info) throws UnsupportedFlavorException, IOException, BiffException {
        try {
            if (info.isDrop()) {
                jTableDatos = (JTable) info.getComponent();
            }
            Transferable t = info.getTransferable();
            File f = (File) t.getTransferData(DataFlavor.javaFileListFlavor);
            try {
                Workbook w = Workbook.getWorkbook(f);
            } catch (BiffException ex) {
                JOptionPane.showMessageDialog(this, ex);
                //Logger.getLogger(Principal.class.getName().log(Level.SEVERE,null,ex));
            }
        } catch (UnsupportedFlavorException | IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16moday;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25a;
    private javax.swing.JTextField jTextField25b0;
    private javax.swing.JTextField jTextField26b;
    private javax.swing.JTextField jTextField26b1;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField27c;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField28d;
    private javax.swing.JTextField jTextField29m;
    private javax.swing.JTextField jTextField29xx;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField30d;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField31ls;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField32li;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldSuma;
    private javax.swing.JTextField jTextFieldSuma1;
    private javax.swing.JTextField jTextField_dediana_X;
    private javax.swing.JTextField jTextField_dediana_Y;
    private javax.swing.JTextField jTextField_max_X;
    private javax.swing.JTextField jTextField_max_Y;
    private javax.swing.JTextField jTextField_min_X;
    private javax.swing.JTextField jTextField_min_Y;
    private javax.swing.JTextField jTextField_ran_X;
    private javax.swing.JTextField jTextField_ran_Y;
    private javax.swing.JTextField jTextFieldmoda;
    // End of variables declaration//GEN-END:variables
}
